### ISSUE TITLE
Use standard Python project structure

### ISSUE THREAD

**Issue by simonwacker** [bbuenoun/trace-glare#1]
For details see [Packaging Python Projects](https://packaging.python.org/tutorials/packaging-projects/).

**Comment by bbuenoun** [comment]
Do you agree with this structure?
trace-glare
├── LICENSE
├── README.md
├── glare
│   └── __init__.py
│   └── trace.py
├── setup.py
└── tests

**Comment by bbuenoun** [comment]
We don't need to generate pip distribution packages for the trace-glare yet, right?

**Comment by simonwacker** [comment]
Yes, that's the standard structure. And yes, there is no need to generate a pip distribution yet. But in the long run distributing the package through pip will increase its potential user base a lot (it's just super easy to install packages with pip and to have pip manage your dependencies with `requirements.txt` files).
