### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by simonwacker** [bbuenoun/trace-glare#3]
Use [pytest](https://docs.pytest.org/en/latest/) for test automation.

**Comment by bbuenoun** [comment]
I checked the pytest routines you made in fener, but I'm not yet able to translate them into a simple test for glare-trace.
Could you please help me? Maybe you can show me some basic functions.
The test would be run "trace-glare/glare$ python trace.py ../test/000 -c 5 -ab 0", and then compare the numerical values of "/trace-glare/test/output/fDGPe_0.out" with those of "/trace-glare/test/output/fDGPe_0_ref.out". The same for "time.out" and "time_ref.out"

**Comment by simonwacker** [comment]
Sure, I'll have a look at it tomorrow.

I added the GNU Make targets [`tests`](https://github.com/bbuenoun/trace-glare/blob/52f35120a87a71e8ab20e8c4d942ea015eef811b/Makefile#L61) and [`doctests`](https://github.com/bbuenoun/trace-glare/blob/52f35120a87a71e8ab20e8c4d942ea015eef811b/Makefile#L65) to run all tests and all doctests with Pytest. They can be executed by running `make tests` and `make doctests` in the command-line.

**Comment by bbuenoun** [comment]
When running make tests, I get the following error (I'm missing this file):

E FileNotFoundError: [Errno 2] No such file or directory: 'tests/test_trace/test_integration/test_simple/actual_output'

/opt/anaconda/anaconda3_7/lib/python3.7/shutil.py:483: FileNotFoundError
